/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jirah.sstoreinventorymanagementsystem;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {


    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    
    public static int user = 0;
    public login() {
        initComponents();
        setLocationRelativeTo(null);

    }
   public java.sql.Connection Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jirahs_store", "root", "");
            st = con.createStatement();
            return con;

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }


    }
    public void UserAdmin() {
        String sql = "Select * from accounts where username='" + username.getText() + "'";
        try {
            st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                String num = rs.getString("ID");
                js_mainmenu.uid.setText(num);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void insertToLogsAdmin(){
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-dd-MM");
    SimpleDateFormat d = new SimpleDateFormat("hh:mm a");
    Date dateobj = new Date();
    String time = d.format(dateobj.getTime());
    String today = sdf.format(dateobj.getTime());
    String fullname = null;
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword())+"'";            
        try {
           pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                fullname = rs.getString("fname")+" "+rs.getString("lname");
            }
            String sign = "INSERT INTO `logs`(`Date`, `Action`, `AccountType`, `Username`)"
                    + "VALUES ('" + today+" "+time + "',' Logged in ','Administrator','"+fullname+"')";                  
                        try {
                    pst = con.prepareStatement(sign);
                    pst.execute();
                        }
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }       
            }      
        catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
    }
     private void insertToLogsUser(){
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-dd-MM");
    SimpleDateFormat d = new SimpleDateFormat("hh:mm a");
    Date dateobj = new Date();
    String time = d.format(dateobj.getTime());
    String today = sdf.format(dateobj.getTime());
    String date = today+" "+time;
    String fullname = null;
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword())+"'";            
        try {
           pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                fullname = rs.getString("fname")+" "+rs.getString("lname");
            }
            String sign = "INSERT INTO `logs`(`Date`, `Action`, `AccountType`, `Username`)"
                    + "VALUES ('" + date + "',' Logged in ','Guest','"+fullname+"')";                  
                        try {
                    pst = con.prepareStatement(sign);
                    pst.execute();
                        }
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }       
            }      
        catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
    }
    private void UserUser(){
        String sql = "Select * from accounts where username='" + username.getText() + "'";
        try {
            st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                String num = rs.getString("ID");
                Sales.uid.setText(num);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_ = new javax.swing.JPanel();
        btn_admin = new javax.swing.JLabel();
        btn_user = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        btn_submit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        banner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jirah's Store");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_.setBackground(new java.awt.Color(255, 255, 255));
        login_.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        login_.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_admin.setBackground(new java.awt.Color(255, 255, 255));
        btn_admin.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(0, 102, 0));
        btn_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_admin.setText("Administrator");
        btn_admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.setOpaque(true);
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adminMouseExited(evt);
            }
        });
        login_.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        btn_user.setBackground(new java.awt.Color(0, 102, 0));
        btn_user.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_user.setText("Guest");
        btn_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        btn_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_user.setOpaque(true);
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_userMouseExited(evt);
            }
        });
        login_.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 280, 40));

        username.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        login_.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 300, 40));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Name_50px.png"))); // NOI18N
        jLabel5.setText("Username:");
        login_.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Password 1_52px.png"))); // NOI18N
        jLabel4.setText("Password:");
        login_.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 50));

        password.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        login_.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 300, 40));

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        show.setForeground(new java.awt.Color(51, 51, 51));
        show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Visible_48px.png"))); // NOI18N
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        login_.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, 20));

        btn_submit.setBackground(new java.awt.Color(0, 102, 0));
        btn_submit.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_submit.setText("Submit");
        btn_submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.setOpaque(true);
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });
        login_.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, 40));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Forgot Password ? ? ?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        login_.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Don't have an account ?");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        login_.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 230, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        login_.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 10, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 0));
        login_.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 560, 10));

        jPanel1.add(login_, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 560, 270));

        banner.setBackground(new java.awt.Color(255, 255, 255));
        banner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sales & Stock Control Management System");
        banner.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 40));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POS ");
        banner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 60));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Minimize.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        banner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 60, 53));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Close Window_64px.png"))); // NOI18N
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        banner.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 60, 53));

        jPanel1.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/6 - Copy.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        banner.setBackground(new java.awt.Color(255, 255, 255, 190));
        login_.setBackground(new java.awt.Color(255, 255, 255, 190));
    }//GEN-LAST:event_formWindowOpened

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        confirm con = new confirm();
        con.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked

        con = Connect();
    if (user == 0){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'Administrator'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       js_mainmenu man = new js_mainmenu();
                       js_mainmenu.jPanel26.setBackground(new java.awt.Color(255,255,255,195));
                       UserAdmin();
                       insertToLogsAdmin();
                       man.setVisible(true);
                        this.dispose();
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }     
    }
    else if(user == 1){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'User'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       Sales man = new Sales();
                       UserUser();
                       insertToLogsUser();
                        man.setVisible(true);
                        this.dispose();
                        user = 0;
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }    
    }


    }//GEN-LAST:event_btn_submitMouseClicked

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        btn_submit.setBackground(new java.awt.Color(255,255,255));
        btn_submit.setForeground(new java.awt.Color(0,102,0));
        btn_submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,0), 2));
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
          btn_submit.setBackground(new java.awt.Color(0,102,0));
          btn_submit.setForeground(new java.awt.Color(255,255,255));
        btn_submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,0), 2));
    }//GEN-LAST:event_btn_submitMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       JOptionPane.showMessageDialog(null, "Please Contact your administrator");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    JOptionPane.showMessageDialog(null, "Please Contact your administrator");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseClicked
    if(btn_user.getBackground().equals(new java.awt.Color(255,255,255))){
        btn_admin.setBackground(new java.awt.Color(255,255,255));
        btn_admin.setForeground(new java.awt.Color(0,102,0));
        btn_user.setBackground(new java.awt.Color(0,102,0));
        btn_user.setForeground(new java.awt.Color(255,255,255));
        user = 0;
    }
    }//GEN-LAST:event_btn_adminMouseClicked

    private void btn_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_adminMouseEntered

    private void btn_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_adminMouseExited

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
    if(btn_admin.getBackground().equals(new java.awt.Color(255,255,255))){
        btn_user.setBackground(new java.awt.Color(255,255,255));
        btn_user.setForeground(new java.awt.Color(0,102,0));
        btn_admin.setBackground(new java.awt.Color(0,102,0));
        btn_admin.setForeground(new java.awt.Color(255,255,255));
        user = 1;
    }
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_userMouseEntered

    private void btn_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_userMouseExited

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        

    }//GEN-LAST:event_formKeyTyped

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
    if( evt.getKeyCode() == KeyEvent.VK_ENTER) {
   con = Connect();
    if (user == 0){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'Administrator'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       js_mainmenu man = new js_mainmenu();
                       UserAdmin();
                       insertToLogsAdmin();
                       man.setVisible(true);
                        this.dispose();
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }     
    }
    else if(user == 1){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'User'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       Sales man = new Sales();
                       UserUser();
                       insertToLogsUser();
                        man.setVisible(true);
                        this.dispose();
                        user = 0;
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }    
    }
        } 
    }//GEN-LAST:event_usernameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
     if( evt.getKeyCode() == KeyEvent.VK_ENTER) {
   con = Connect();
    if (user == 0){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'Administrator'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       js_mainmenu man = new js_mainmenu();
                       UserAdmin();
                       insertToLogsAdmin();
                       man.setVisible(true);
                        this.dispose();
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }     
    }
    else if(user == 1){
            if (username.getText().equals("") || String.valueOf(password.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Either username or password is empty.");
            } else {
                String sql = "Select * from accounts where username='" + username.getText() + "' and password='" + String.valueOf(password.getPassword()) + "' AND AccountType = 'User'";
                try {
                    st = con.createStatement();
                    rs = st.executeQuery(sql);
                    if (rs.next()){
                       Sales man = new Sales();
                       UserUser();
                       insertToLogsUser();
                        man.setVisible(true);
                        this.dispose();
                        user = 0;
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, " Invalid Username or Password");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }    
    }
        } 
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if (show.isSelected()) {
            password.setEchoChar((char) 0);
            show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Invisible_48px.png")));
        } else {
            password.setEchoChar('*');
            show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jirah/icons/Visible_48px.png")));
        }
    }//GEN-LAST:event_showActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        banner.setBackground(new java.awt.Color(255, 255, 255, 190));
        login_.setBackground(new java.awt.Color(255, 255, 255, 190));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel banner;
    private javax.swing.JLabel btn_admin;
    private javax.swing.JLabel btn_submit;
    private javax.swing.JLabel btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JPanel login_;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox show;
    private javax.swing.JTextField username;
}
